### ISSUE TITLE
API Key invalid

### ISSUE THREAD

**Issue by UNICodehORN** [GameHQ702/Serienstream-API-Wrapper#1]
Seems like the API Key was invalidated?!

**Comment by GameHQ702** [comment]
I don't think so, can you tell me which request you are having problems with?

**Comment by UNICodehORN** [comment]
Thanks for the fast reply. 
E.g. this link should give info about a series:
https://serienstream.sx/api/v1/series/get?series=1234&key=9bmkkkvloi4o10pnel886l1xj6ztycualnmofbkrsfzsmc26lrujoesptp8aqw

But I keep getting a 403 not authorized.

**Comment by GameHQ702** [comment]
oh, it looks like the request has been removed.

**Comment by GameHQ702** [comment]
to get a series you can also fetch all series and then match them.

**Comment by GameHQ702** [comment]
works now again was a problem at s.to.
